## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if .Values.adb.ocid }}
{{- $mtlsWallet := include "getMtlsWallet" . | fromJson }}
{{- if not $mtlsWallet.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oaim.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
stringData:
  {{ include "oaim.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}: {{ randAlphaNum 16 | quote }}
{{- end }}
---
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: {{ include "oaim.fullname" . }}-adb
  labels: 
    {{- include "oaim.labels" . | nindent 4 }}
spec:
  details:
    autonomousDatabaseOCID: {{ .Values.adb.ocid }}
    wallet:
      name: {{ include "oaim.fullname" . }}-adb-tns-admin-{{ .Release.Revision }}
      password:
        k8sSecret:
          name: {{ include "oaim.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}
{{ end }}