## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if .Values.database.ocid }}
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: {{ include "oaim.fullname" . }}-adb
  labels: 
    {{- include "oaim.labels" . | nindent 4 }}
spec:
  details:
    autonomousDatabaseOCID: {{ .Values.database.ocid }}
    wallet:
      name: {{ include "oaim.fullname" . }}-adb-tns-admin-{{ .Release.Revision }}
      password:
        k8sSecret:
          name: {{ include "oaim.fullname" . }}-adb-wallet-pass-{{ .Release.Revision }}
  ociConfig:
    configMapName: {{ include "oaim.fullname" . }}-oci-region
{{ end }}