## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oaim.fullname" . }}
  labels:
    {{- include "oaim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oaim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oaim.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oaim.serviceAccountName" . }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.database.enabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.authN.secretName | quote }}
                  key: {{ .Values.database.authN.usernameKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.authN.secretName | quote }}
                  key: {{ .Values.database.authN.passwordKey | quote }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.authN.secretName | quote }}
                  key: {{ .Values.database.authN.serviceKey | quote }}
            {{- $mtlsWallet := include "getMtlsWallet" . | fromJson }}
            {{- if $mtlsWallet.secretName }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $mtlsWallet.secretName | quote }}
                  key: {{ $mtlsWallet.secretKey | quote }}
            {{ else }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: default-db-wallet-pass-{{ .Release.Revision }}
                  key: default-db-wallet-pass-{{ .Release.Revision }}
            {{- end }}
            {{- end }}
            - name: API_SERVER_PORT
              value: 8000
            - name: API_SERVER_KEY
              valueFrom:
                secretKeyRef:
              {{- if and .Values.server.api.secretName .Values.server.api.secretKey }}
                  name: {{ .Values.server.api.secretName }}
                  key: {{ .Values.server.api.secretKey }}
              {{- else }}
                  name: {{ include "release.name" . }}-api-key
                  key: "apiKey"
              {{- end }}
            {{- with .Values }}
            {{- if .models }}
            {{- if and .models.openAI .models.openAI.secretName }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.openAI.secretName }}
                  key: {{ .models.openAI.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.perplexity .models.perplexity.secretName }}
            - name: PPLX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.perplexity.secretName }}
                  key: {{ .models.perplexity.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.cohere .models.cohere.secretName }}
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.cohere.secretName }}
                  key: {{ .models.cohere.secretKey | default "apiKey" }}
            {{- end }}
            {{- if and .models.ollama .models.ollama.urlPort }}
            - name: ON_PREM_OLLAMA_URL
              value: {{ .models.ollama.urlPort }}
            {{- end }}
            {{- if and .models.ollama .models.huggingface.urlPort }}
            - name: ON_PREM_HF_URL
              value: {{ .models.huggingface.urlPort }}
            {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/app/tmp"
            {{- if .Values.database.enabled }}
            - name: tns-admin
              mountPath: /app/tns_admin
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.database.enabled }}
        - name: tns-admin
          secret:
            {{- $tnsAdmin := include "getTnsAdmin" . | fromJson }}
            {{- if $tnsAdmin.secretName }}
            secretName: {{ $tnsAdmin.secretName | quote }}
            {{ else }}
            secretName: {{ include "oaim.fullname" . }}-adb-tns-admin-{{ .Release.Revision }}
            {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
