## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.name" . }}-api-key
  labels: 
    {{- include "oaim.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.server.apiKey }}
data:
  apiKey: {{ .Values.server.apiKey | b64enc }}
{{- else if not .Values.server.secretName }}
data:
  apiKey: {{ randAlphaNum 32 | b64enc }}
{{- end }}