## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oaim-sandbox.fullname" . }}
  labels:
    {{- include "oaim-sandbox.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oaim-sandbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oaim-sandbox.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oaim-sandbox.serviceAccountName" . }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ include "getPath" . | quote }}
              port: http
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: TEMP
              value: "/app/tmp"
            - name: NUMBA_CACHE_DIR
              value: "/app/tmp"
            - name: MPLCONFIGDIR
              value: "/app/tmp"
            - name: REPORTS_DIR
              value: "/app/reports"
            - name: DISABLE_OCI
              value: "true"
            {{- if .Values.oaimSandbox.database.enabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oaimSandbox.database.authN.secretName | quote }}
                  key: {{ .Values.oaimSandbox.database.authN.usernameKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oaimSandbox.database.authN.secretName | quote }}
                  key: {{ .Values.oaimSandbox.database.authN.passwordKey | quote }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oaimSandbox.database.authN.secretName | quote }}
                  key: {{ .Values.oaimSandbox.database.authN.serviceKey | quote }}
            {{- $mtlsWallet := include "getMtlsWallet" . | fromJson }}
            {{- if $mtlsWallet.secretName }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $mtlsWallet.secretName | quote }}
                  key: {{ $mtlsWallet.secretKey | quote }}
            {{ else }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oaimSandbox.database.name | lower }}-db-wallet-pass-{{ .Release.Revision }}
                  key: {{ .Values.oaimSandbox.database.name | lower }}-db-wallet-pass-{{ .Release.Revision }}       
            {{- end }}
            {{- end }}
            {{- with .Values.oaimSandbox }}
            {{- if eq .disableTools "true" }}
            - name: DISABLE_TOOLS
              value: "true"
            {{- end }}
            {{- if eq .disableTests "true" }}
            - name: DISABLE_TESTS
              value: "true"
            {{- end }}
            {{- if eq .disableAdmin "true" }}
            - name: DISABLE_ADMIN
              value: "true"
            {{- end }}
            {{- if eq .disableAAPI "true" }}
            - name: DISABLE_API
              value: "true"
            {{- end }}
            {{- if .models }}
            {{- if .models.openAI.secretName }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.openAI.secretName }}
                  key: {{ .models.openAI.secretKey }}
            {{- end }}
            {{- if .models.perplexity.secretName }}
            - name: PPLX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.perplexity.secretName }}
                  key: {{ .models.perplexity.secretKey }}
            {{- end }}
            {{- if .models.cohere.secretName }}
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .models.cohere.secretName }}
                  key: {{ .models.cohere.secretKey }}
            {{- end }}
            {{- end }}
            {{- end }}

          volumeMounts:
            - name: tmp
              mountPath: /app/tmp
            - name: reports
              mountPath: /app/reports
            - name: streamlit-config
              mountPath: /app/.streamlit
            {{- if .Values.oaimSandbox.database.enabled }}
            - name: tns-admin
              mountPath: /app/tns_admin
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: reports
          emptyDir: {}
        - name: streamlit-config
          configMap:
            name: {{ .Chart.Name }}-streamlit-config
        {{- if .Values.oaimSandbox.database.enabled }}
        - name: tns-admin
          secret:
            {{- $tnsAdmin := include "getTnsAdmin" . | fromJson }}
            {{- if $tnsAdmin.secretName }}
            secretName: {{ $tnsAdmin.secretName | quote }}
            {{ else }}
            secretName: {{ .Values.oaimSandbox.database.name | lower }}-tns-admin-{{ .Release.Revision }}
            {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
