## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if not .Values.oaimSandbox.database.mtlsWallet.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oaimSandbox.database.name | lower }}-db-wallet-pass-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
stringData:
  {{ .Values.oaimSandbox.database.name | lower }}-db-wallet-pass-{{ .Release.Revision }}: {{ randAlphaNum 16 | quote }}
{{- end }}