## Copyright (c) 2023, 2024, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "oaim-sandbox.fullname" . }}-http
  labels: 
    {{- include "oaim-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "oaim-sandbox.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oaim-sandbox.fullname" . }}-api
  labels: 
    {{- include "oaim-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: api
  selector: 
    {{- include "oaim-sandbox.selectorLabels" . | nindent 4 }}
{{- end }}