# Copyright © 2023, 2025, Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Oracle AI Explorer for Apps"
description: "Explore the capabilities of AI with the Oracle Database."
schemaVersion: 1.1.0
version: "20190304"
logoUrl: https://github.com/oracle-samples/ai-explorer/blob/main/docs/static/images/logo.png
locale: "en"

variableGroups:
  #########################################################################
  # Hidden
  #########################################################################
  - title: "Default Hidden"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - current_user_ocid
      - fingerprint
      - private_key_path
      - private_key
    visible: false

  - title: "Hidden (Defaults)"
    variables:
      - adb_version
      - k8s_version
      - k8s_worker_os_ver
      - service_lb_allowed_app_client_port
      - service_lb_allowed_app_server_port
    visible: false

  #########################################################################
  # General (Backend as a Service)
  #########################################################################
  - title: "AI Explorer"
    variables:
      - compartment_ocid
      - label_prefix
    visible: true

  #########################################################################
  # Database
  #########################################################################
  - title: "Database Options"
    variables:
      - adb_license_model
      - adb_edition
      - adb_whitelist_cidrs
      - adb_ecpu_core_count
      - adb_is_cpu_auto_scaling_enabled
      - adb_data_storage_size_in_gb
      - adb_is_storage_auto_scaling_enabled
    visible: true

  #########################################################################
  # Kubernetes Cluster
  #########################################################################
  - title: "Kubernetes Cluster Options"
    variables:
      - k8s_api_is_public
      - k8s_api_endpoint_allowed_cidrs
      - k8s_node_pool_cpu_size
      - k8s_worker_cpu_shape
      - k8s_worker_cpu_ocpu
      - k8s_node_pool_gpu_deploy
      - k8s_node_pool_gpu_size
      - k8s_worker_gpu_shape
    visible: true

  #########################################################################
  # Load Balancer
  #########################################################################
  - title: "Load Balancers Options"
    variables:
      - service_lb_is_public
      - service_lb_min_shape
      - service_lb_max_shape
      - service_lb_allowed_app_client_cidrs
      - service_lb_allowed_app_server_cidrs

    visible: true

###########################################################################
variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    required: true

  label_prefix:
    type: string
    title: "Application Name"
    pattern: "^$|^[a-zA-Z0-9]{1,12}$"
    required: false

  #########################################################################
  adb_license_model:
    type: enum
    title: "Autonomous Database License Model"
    required: true
    default: "LICENSE_INCLUDED"
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  adb_edition:
    type: enum
    title: "Oracle Database Edition"
    required: true
    default: "ENTERPRISE_EDITION"
    enum:
      - "ENTERPRISE_EDITION"
      - "STANDARD_EDITION"
    visible:
      and:
        - eq:
            - adb_license_model
            - BRING_YOUR_OWN_LICENSE

  adb_whitelist_cidrs:
    type: array
    title: "ADB Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"

  adb_ecpu_core_count:
    type: number
    title: "Autonomous Database Core Count"
    required: true
    minimum: 2
    multipleOf: 1

  adb_is_cpu_auto_scaling_enabled:
    type: boolean
    title: "Allow Autonomous Database CPU Auto Scaling? (3x CPU)"
    required: true

  adb_data_storage_size_in_gb:
    type: number
    title: "Autonomous Database Data Storage Size (GB)"
    description: ""
    required: true
    minimum: 20
    maximum: 393216
    multipleOf: 1

  adb_is_storage_auto_scaling_enabled:
    type: boolean
    title: "Allow Autonomous Database Storage Auto Scaling?"
    required: true

  #########################################################################
  k8s_api_is_public:
    type: boolean
    title: "Public API Endpoint?"
    required: true

  k8s_api_endpoint_allowed_cidrs:
    type: array
    title: "API Endpoint Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "$|((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible: k8s_api_is_public

  k8s_node_pool_cpu_size:
    type: integer
    title: "CPU Node Pool Workers"
    required: true
    minimum: 1
    maximum: 80
    multipleOf: 1

  k8s_worker_cpu_shape:
    type: enum
    title: "CPU Node Pool Worker Shape"
    required: true
    enum:
      - "VM.Standard.E5.Flex"
      - "VM.Standard.E4.Flex"

  k8s_worker_cpu_ocpu:
    type: integer
    title: "CPU Worker Core Count"
    required: true
    minimum: 1
    maximum: 64
    multipleOf: 1

  k8s_node_pool_gpu_deploy:
    type: boolean
    title: "Deploy GPU Node Pool?"
    required: true

  k8s_worker_gpu_shape:
    type: enum
    title: "Node Pool Worker Shape"
    required: true
    default: "VM.GPU.A10.1"
    enum:
      - "VM.GPU.A10.1"
    visible: k8s_node_pool_gpu_deploy

  k8s_node_pool_gpu_size:
    type: integer
    title: "GPU Node Pool Workers"
    required: true
    minimum: 1
    maximum: 80
    multipleOf: 1
    visible: k8s_node_pool_gpu_deploy

  #########################################################################
  service_lb_is_public:
    type: boolean
    title: "Enable Ingress through Public Load Balancer?"
    default: true

  service_lb_min_shape:
    type: integer
    title: "Minimum Load Balancer Bandwidth (Mbps)"
    required: true
    minimum: 10
    maximum: 10
    multipleOf: 10
    visible: service_lb_is_public

  service_lb_max_shape:
    type: integer
    title: "Maximum Load Balancer Bandwidth (Mbps)"
    required: true
    minimum: 10
    maximum: 8000
    multipleOf: 10
    visible: service_lb_is_public

  service_lb_allowed_app_client_cidrs:
    type: array
    title: "Public Load Balancer Access Control for GUI"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible: service_lb_is_public

  service_lb_allowed_app_server_cidrs:
    type: array
    title: "Public Load Balancer Access Control for Application Server"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible: service_lb_is_public
