---
apiVersion: v1
kind: Namespace
metadata:
  name: ${label}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${adb_name}-authn
  namespace: ${label}
type: Opaque
stringData:
  username: ADMIN
  password: ${adb_password}
  service: ${adb_service}
---
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
  namespace: ${label}
spec:
  compartmentId: ${compartment_ocid}
  subnetId: ${lb_subnet_ocid}
  loadBalancerName: "${label}-lb"
  reservedPublicAddressId: ${lb_ip_ocid}
  isPrivate: false
  maxBandwidthMbps: 100
  minBandwidthMbps: 10
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic
  namespace: ${label}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    oci-native-ingress.oraclecloud.com/network-security-group-ids: ${lb_nsgs}
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: ${label}
    apiGroup: ingress.oraclecloud.com
    kind: IngressClassParameters
    name: native-ic-params