## Copyright (c) 2024-2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "oaim.fullname" . }}-http
  labels: 
    {{- include "oaim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: 8501
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "oaim.selectorLabels" . | nindent 4 }}