server:
  servlet:
    context-path: /v1
spring:
  datasource:
    url: ${{spring.datasource.url]}}
    username: ${{spring.datasource.username]}}
    password: ${{spring.datasource.password]}}
  ai:
    vectorstore:
      oracle:
        distance-type: {rag[distance_metric]}
        remove-existing-vector-store-table: True
        initialize-schema: True
        index-type: None
    openai:
      base-url: \"{ll_model[url]}\"
      api-key:  \"{ll_model[api_key]}\"
      chat:
        options:
          temperature: {ll_model[temperature]}
          presencePenalty: {ll_model[presence_penalty]}
          frequencyPenalty: {ll_model[frequency_penalty]}
          maxTokens: {ll_model[max_completion_tokens]}
          topP: {ll_model[top_p]}
          model: {ll_model[model]}
      embedding:
        options:
          model: {rag[model]}
    ollama:
      base-url: "http://ollama.ollama.svc.cluster.local:11434"
      chat:
        options:
          temperature: {ll_model[temperature]}
          presence-penalty: {ll_model[presence_penalty]}
          frequency-penalty: {ll_model[frequency_penalty]}
          num-predict: {ll_model[max_completion_tokens]}
          top-p: {ll_model[top_p]}
          model: \"{ll_model[model]}\"
      embedding:
        options: 
          model: \"{rag[model]}\"        
aims:
  context_instr: \"{ctx_prompt}\"
  vectortable:
    name: {rag[vector_store]}
  rag_params: 
    search_type: Similarity
    top_k: {rag[top_k]}
