## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v2
name: ai-explorer
description: A Helm chart Oracle AI Explorer for Apps
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Oracle
    email: obaas_ww@oracle.com
    url: https://github.com/oracle-samples/ai-explorer

dependencies:
  - name: ai-explorer-server
    version: 0.1.0
    repository: file://charts/ai-explorer-server
    condition: ai-explorer-server.enabled
  - name: ai-explorer-client
    version: 0.1.0
    repository: file://charts/ai-explorer-client
    condition: ai-explorer-client.enabled
  - name: ollama
    version: 0.1.0
    repository: file://charts/ollama
    condition: ollama.enabled