## Copyright (c) 2024-2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v2
name: oaim-sandbox
description: A Helm chart Oracle AI Microservice Sandbox
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Oracle
    email: obaas_ww@oracle.com
    url: https://github.com/oracle-samples/oaim-sandbox

dependencies:
  - name: oaim-server
    version: 0.1.0
    repository: file://charts/oaim-server
    condition: oaim-server.enabled
  - name: oaim-sandbox
    version: 0.1.0
    repository: file://charts/oaim-sandbox
    condition: oaim-sandbox.enabled
  - name: ollama
    version: 0.1.0
    repository: file://charts/ollama
    condition: ollama.enabled